//-----------------------------------------------------------------------------
// Copyright (c) Microsoft Corporation.  All rights reserved.
//-----------------------------------------------------------------------------
// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("StyleCop.CSharp.OrderingRules", "SA1201:Elements should appear in the correct order", Justification = "<Pending>", Scope = "member", Target = "~F:Microsoft.Liftr.ACIS.DatadogManagementExtension.s_redirectDllList")]
[assembly: SuppressMessage("Reliability", "Liftr1004:Avoid calling System.Threading.Tasks.Task<TResult>.Result", Justification = "<Pending>", Scope = "member", Target = "~M:Microsoft.Liftr.ACIS.GetDatadogMonitorOperation.GetDatadogMonitor(System.String,Microsoft.WindowsAzure.Wapd.Acis.Contracts.IAcisServiceManagementExtension,Microsoft.WindowsAzure.Wapd.Acis.Contracts.IAcisSMEOperationProgressUpdater,Microsoft.WindowsAzure.Wapd.Acis.Contracts.IAcisSMEEndpoint)~Microsoft.WindowsAzure.Wapd.Acis.Contracts.IAcisSMEOperationResponse")]
[assembly: SuppressMessage("Reliability", "Liftr1004:Avoid calling System.Threading.Tasks.Task<TResult>.Result", Justification = "<Pending>", Scope = "member", Target = "~M:Microsoft.Liftr.ACIS.GetRelationshipsByResourceOperation.GetRelationshipsByResource(System.String,Microsoft.WindowsAzure.Wapd.Acis.Contracts.IAcisServiceManagementExtension,Microsoft.WindowsAzure.Wapd.Acis.Contracts.IAcisSMEOperationProgressUpdater,Microsoft.WindowsAzure.Wapd.Acis.Contracts.IAcisSMEEndpoint)~Microsoft.WindowsAzure.Wapd.Acis.Contracts.IAcisSMEOperationResponse")]
[assembly: SuppressMessage("Reliability", "Liftr1004:Avoid calling System.Threading.Tasks.Task<TResult>.Result", Justification = "<Pending>", Scope = "member", Target = "~M:Microsoft.Liftr.ACIS.GetRelationshipsByMonitorOperation.GetRelationshipsByMonitor(System.String,Microsoft.WindowsAzure.Wapd.Acis.Contracts.IAcisServiceManagementExtension,Microsoft.WindowsAzure.Wapd.Acis.Contracts.IAcisSMEOperationProgressUpdater,Microsoft.WindowsAzure.Wapd.Acis.Contracts.IAcisSMEEndpoint)~Microsoft.WindowsAzure.Wapd.Acis.Contracts.IAcisSMEOperationResponse")]
[assembly: SuppressMessage("Reliability", "Liftr1004:Avoid calling System.Threading.Tasks.Task<TResult>.Result", Justification = "<Pending>", Scope = "member", Target = "~M:Microsoft.Liftr.ACIS.RemoveRelationshipByResourceOperation.RemoveRelationshipByResource(System.String,System.String,Microsoft.WindowsAzure.Wapd.Acis.Contracts.IAcisServiceManagementExtension,Microsoft.WindowsAzure.Wapd.Acis.Contracts.IAcisSMEOperationProgressUpdater,Microsoft.WindowsAzure.Wapd.Acis.Contracts.IAcisSMEEndpoint)~Microsoft.WindowsAzure.Wapd.Acis.Contracts.IAcisSMEOperationResponse")]
[assembly: SuppressMessage("Reliability", "Liftr1004:Avoid calling System.Threading.Tasks.Task<TResult>.Result", Justification = "<Pending>", Scope = "member", Target = "~M:Microsoft.Liftr.ACIS.GetMonitorsBySubscriptionOperation.GetMonitorsBySubscription(System.String,Microsoft.WindowsAzure.Wapd.Acis.Contracts.IAcisServiceManagementExtension,Microsoft.WindowsAzure.Wapd.Acis.Contracts.IAcisSMEOperationProgressUpdater,Microsoft.WindowsAzure.Wapd.Acis.Contracts.IAcisSMEEndpoint)~Microsoft.WindowsAzure.Wapd.Acis.Contracts.IAcisSMEOperationResponse")]
[assembly: SuppressMessage("Reliability", "Liftr1004:Avoid calling System.Threading.Tasks.Task<TResult>.Result", Justification = "<Pending>", Scope = "member", Target = "~M:Microsoft.Liftr.ACIS.GetMarketplaceResourceByMonitorOperation.GetMarketplaceResourceByMonitor(System.String,Microsoft.WindowsAzure.Wapd.Acis.Contracts.IAcisServiceManagementExtension,Microsoft.WindowsAzure.Wapd.Acis.Contracts.IAcisSMEOperationProgressUpdater,Microsoft.WindowsAzure.Wapd.Acis.Contracts.IAcisSMEEndpoint)~Microsoft.WindowsAzure.Wapd.Acis.Contracts.IAcisSMEOperationResponse")]
[assembly: SuppressMessage("Reliability", "Liftr1004:Avoid calling System.Threading.Tasks.Task<TResult>.Result", Justification = "<Pending>", Scope = "member", Target = "~M:Microsoft.Liftr.ACIS.ListAllMonitorsOperation.ListAllMonitors(System.String,Microsoft.WindowsAzure.Wapd.Acis.Contracts.IAcisServiceManagementExtension,Microsoft.WindowsAzure.Wapd.Acis.Contracts.IAcisSMEOperationProgressUpdater,Microsoft.WindowsAzure.Wapd.Acis.Contracts.IAcisSMEEndpoint)~Microsoft.WindowsAzure.Wapd.Acis.Contracts.IAcisSMEOperationResponse")]
[assembly: SuppressMessage("Reliability", "Liftr1004:Avoid calling System.Threading.Tasks.Task<TResult>.Result", Justification = "<Pending>", Scope = "member", Target = "~M:Microsoft.Liftr.ACIS.GetMonitorTagRulesOperation.GetMonitorTagRules(System.String,Microsoft.WindowsAzure.Wapd.Acis.Contracts.IAcisServiceManagementExtension,Microsoft.WindowsAzure.Wapd.Acis.Contracts.IAcisSMEOperationProgressUpdater,Microsoft.WindowsAzure.Wapd.Acis.Contracts.IAcisSMEEndpoint)~Microsoft.WindowsAzure.Wapd.Acis.Contracts.IAcisSMEOperationResponse")]
[assembly: SuppressMessage("Reliability", "Liftr1004:Avoid calling System.Threading.Tasks.Task<TResult>.Result", Justification = "<Pending>", Scope = "member", Target = "~M:Microsoft.Liftr.ACIS.GetStatusByMonitorOperation.GetStatusByMonitor(System.String,Microsoft.WindowsAzure.Wapd.Acis.Contracts.IAcisServiceManagementExtension,Microsoft.WindowsAzure.Wapd.Acis.Contracts.IAcisSMEOperationProgressUpdater,Microsoft.WindowsAzure.Wapd.Acis.Contracts.IAcisSMEEndpoint)~Microsoft.WindowsAzure.Wapd.Acis.Contracts.IAcisSMEOperationResponse")]
[assembly: SuppressMessage("Reliability", "Liftr1004:Avoid calling System.Threading.Tasks.Task<TResult>.Result", Justification = "<Pending>", Scope = "member", Target = "~M:Microsoft.Liftr.ACIS.GetStatusByResourceOperation.GetStatusByResource(System.String,Microsoft.WindowsAzure.Wapd.Acis.Contracts.IAcisServiceManagementExtension,Microsoft.WindowsAzure.Wapd.Acis.Contracts.IAcisSMEOperationProgressUpdater,Microsoft.WindowsAzure.Wapd.Acis.Contracts.IAcisSMEEndpoint)~Microsoft.WindowsAzure.Wapd.Acis.Contracts.IAcisSMEOperationResponse")]
[assembly: SuppressMessage("Reliability", "Liftr1004:Avoid calling System.Threading.Tasks.Task<TResult>.Result", Justification = "<Pending>", Scope = "member", Target = "~M:Microsoft.Liftr.ACIS.Datadog.Migration.MigrateMonitorOperation.MigrateMonitor(System.String,Microsoft.WindowsAzure.Wapd.Acis.Contracts.IAcisServiceManagementExtension,Microsoft.WindowsAzure.Wapd.Acis.Contracts.IAcisSMEOperationProgressUpdater,Microsoft.WindowsAzure.Wapd.Acis.Contracts.IAcisSMEEndpoint)~Microsoft.WindowsAzure.Wapd.Acis.Contracts.IAcisSMEOperationResponse")]
[assembly: SuppressMessage("Reliability", "Liftr1004:Avoid calling System.Threading.Tasks.Task<TResult>.Result", Justification = "<Pending>", Scope = "member", Target = "~M:Microsoft.Liftr.ACIS.Datadog.Migration.MigrateSubscriptionOperation.MigrateSubscription(System.String,Microsoft.WindowsAzure.Wapd.Acis.Contracts.IAcisServiceManagementExtension,Microsoft.WindowsAzure.Wapd.Acis.Contracts.IAcisSMEOperationProgressUpdater,Microsoft.WindowsAzure.Wapd.Acis.Contracts.IAcisSMEEndpoint)~Microsoft.WindowsAzure.Wapd.Acis.Contracts.IAcisSMEOperationResponse")]
[assembly: SuppressMessage("Reliability", "Liftr1004:Avoid calling System.Threading.Tasks.Task<TResult>.Result", Justification = "<Pending>", Scope = "member", Target = "~M:Microsoft.Liftr.ACIS.GetStatusByResourceOperation.GetStatusByResource(System.String,Microsoft.WindowsAzure.Wapd.Acis.Contracts.IAcisServiceManagementExtension,Microsoft.WindowsAzure.Wapd.Acis.Contracts.IAcisSMEOperationProgressUpdater,Microsoft.WindowsAzure.Wapd.Acis.Contracts.IAcisSMEEndpoint)~Microsoft.WindowsAzure.Wapd.Acis.Contracts.IAcisSMEOperationResponse")]
[assembly: SuppressMessage("Reliability", "Liftr1004:Avoid calling System.Threading.Tasks.Task<TResult>.Result", Justification = "<Pending>", Scope = "member", Target = "~M:Microsoft.Liftr.ACIS.GetExistingRelationshipsOperation.GetExistingRelationships(System.String,Microsoft.WindowsAzure.Wapd.Acis.Contracts.IAcisServiceManagementExtension,Microsoft.WindowsAzure.Wapd.Acis.Contracts.IAcisSMEOperationProgressUpdater,Microsoft.WindowsAzure.Wapd.Acis.Contracts.IAcisSMEEndpoint)~Microsoft.WindowsAzure.Wapd.Acis.Contracts.IAcisSMEOperationResponse")]
[assembly: SuppressMessage("Reliability", "Liftr1004:Avoid calling System.Threading.Tasks.Task<TResult>.Result", Justification = "<Pending>", Scope = "member", Target = "~M:Microsoft.Liftr.ACIS.Datadog.Migration.AddSubscriptionToV1Operation.AddSubscriptionToV1(System.String,Microsoft.WindowsAzure.Wapd.Acis.Contracts.IAcisServiceManagementExtension,Microsoft.WindowsAzure.Wapd.Acis.Contracts.IAcisSMEOperationProgressUpdater,Microsoft.WindowsAzure.Wapd.Acis.Contracts.IAcisSMEEndpoint)~Microsoft.WindowsAzure.Wapd.Acis.Contracts.IAcisSMEOperationResponse")]
[assembly: SuppressMessage("Reliability", "Liftr1004:Avoid calling System.Threading.Tasks.Task<TResult>.Result", Justification = "<Pending>", Scope = "member", Target = "~M:Microsoft.Liftr.ACIS.Datadog.Migration.DeleteSubscriptionOperation.DeleteSubscription(System.String,Microsoft.WindowsAzure.Wapd.Acis.Contracts.IAcisServiceManagementExtension,Microsoft.WindowsAzure.Wapd.Acis.Contracts.IAcisSMEOperationProgressUpdater,Microsoft.WindowsAzure.Wapd.Acis.Contracts.IAcisSMEEndpoint)~Microsoft.WindowsAzure.Wapd.Acis.Contracts.IAcisSMEOperationResponse")]
[assembly: SuppressMessage("Reliability", "Liftr1004:Avoid calling System.Threading.Tasks.Task<TResult>.Result", Justification = "<Pending>", Scope = "member", Target = "~M:Microsoft.Liftr.ACIS.GetMaxDiagnosticSettingCountOperation.GetMaxDiagnosticSettingCount(System.String,Microsoft.WindowsAzure.Wapd.Acis.Contracts.IAcisServiceManagementExtension,Microsoft.WindowsAzure.Wapd.Acis.Contracts.IAcisSMEOperationProgressUpdater,Microsoft.WindowsAzure.Wapd.Acis.Contracts.IAcisSMEEndpoint)~Microsoft.WindowsAzure.Wapd.Acis.Contracts.IAcisSMEOperationResponse")]
