//-----------------------------------------------------------------------------
// Copyright (c) Microsoft Corporation.  All rights reserved.
//-----------------------------------------------------------------------------
// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("Globalization", "CA1305:Specify IFormatProvider", Justification = "<Pending>", Scope = "member", Target = "~M:Microsoft.Liftr.ACIS.Logz.LogzExtension.OnLoad~System.Boolean")]
[assembly: SuppressMessage("Globalization", "CA1305:Specify IFormatProvider", Justification = "<Pending>", Scope = "member", Target = "~M:Microsoft.Liftr.ACIS.Logz.LogzExtension.OnEndpointCreate(Microsoft.WindowsAzure.Wapd.Acis.Contracts.IAcisSMEEndpoint)~System.Boolean")]
[assembly: SuppressMessage("StyleCop.CSharp.OrderingRules", "SA1201:Elements should appear in the correct order", Justification = "<Pending>", Scope = "member", Target = "~F:Microsoft.Liftr.ACIS.Logz.LogzExtension.s_redirectDllList")]
[assembly: SuppressMessage("Reliability", "Liftr1004:Avoid calling System.Threading.Tasks.Task<TResult>.Result", Justification = "<Pending>", Scope = "member", Target = "~M:Microsoft.Liftr.ACIS.Logz.GetLogzMonitorOperation.GetLogzMonitor(System.String,Microsoft.WindowsAzure.Wapd.Acis.Contracts.IAcisServiceManagementExtension,Microsoft.WindowsAzure.Wapd.Acis.Contracts.IAcisSMEOperationProgressUpdater,Microsoft.WindowsAzure.Wapd.Acis.Contracts.IAcisSMEEndpoint)~Microsoft.WindowsAzure.Wapd.Acis.Contracts.IAcisSMEOperationResponse")]
[assembly: SuppressMessage("Reliability", "Liftr1004:Avoid calling System.Threading.Tasks.Task<TResult>.Result", Justification = "<Pending>", Scope = "member", Target = "~M:Microsoft.Liftr.ACIS.Logz.GetRelationshipsByMonitoredResourceOperation.GetRelationshipsByMonitoredResource(System.String,Microsoft.WindowsAzure.Wapd.Acis.Contracts.IAcisServiceManagementExtension,Microsoft.WindowsAzure.Wapd.Acis.Contracts.IAcisSMEOperationProgressUpdater,Microsoft.WindowsAzure.Wapd.Acis.Contracts.IAcisSMEEndpoint)~Microsoft.WindowsAzure.Wapd.Acis.Contracts.IAcisSMEOperationResponse")]
[assembly: SuppressMessage("Reliability", "Liftr1004:Avoid calling System.Threading.Tasks.Task<TResult>.Result", Justification = "<Pending>", Scope = "member", Target = "~M:Microsoft.Liftr.ACIS.Logz.GetRelationshipsByMonitorOperation.GetRelationshipsByMonitor(System.String,Microsoft.WindowsAzure.Wapd.Acis.Contracts.IAcisServiceManagementExtension,Microsoft.WindowsAzure.Wapd.Acis.Contracts.IAcisSMEOperationProgressUpdater,Microsoft.WindowsAzure.Wapd.Acis.Contracts.IAcisSMEEndpoint)~Microsoft.WindowsAzure.Wapd.Acis.Contracts.IAcisSMEOperationResponse")]
[assembly: SuppressMessage("Reliability", "Liftr1004:Avoid calling System.Threading.Tasks.Task<TResult>.Result", Justification = "<Pending>", Scope = "member", Target = "~M:Microsoft.Liftr.ACIS.Logz.RemoveRelationshipByResourceOperation.RemoveRelationshipByResource(System.String,System.String,Microsoft.WindowsAzure.Wapd.Acis.Contracts.IAcisServiceManagementExtension,Microsoft.WindowsAzure.Wapd.Acis.Contracts.IAcisSMEOperationProgressUpdater,Microsoft.WindowsAzure.Wapd.Acis.Contracts.IAcisSMEEndpoint)~Microsoft.WindowsAzure.Wapd.Acis.Contracts.IAcisSMEOperationResponse")]
[assembly: SuppressMessage("Reliability", "Liftr1004:Avoid calling System.Threading.Tasks.Task<TResult>.Result", Justification = "<Pending>", Scope = "member", Target = "~M:Microsoft.Liftr.ACIS.Logz.GetMonitorCreationStatusByMonitorOperation.GetMonitorCreationStatusByMonitor(System.String,Microsoft.WindowsAzure.Wapd.Acis.Contracts.IAcisServiceManagementExtension,Microsoft.WindowsAzure.Wapd.Acis.Contracts.IAcisSMEOperationProgressUpdater,Microsoft.WindowsAzure.Wapd.Acis.Contracts.IAcisSMEEndpoint)~Microsoft.WindowsAzure.Wapd.Acis.Contracts.IAcisSMEOperationResponse")]
[assembly: SuppressMessage("Reliability", "Liftr1004:Avoid calling System.Threading.Tasks.Task<TResult>.Result", Justification = "<Pending>", Scope = "member", Target = "~M:Microsoft.Liftr.ACIS.Logz.UpdateMonitorCreationStatusByMonitorOperation.UpdateMonitorCreationStatusByMonitor(System.String,System.String,System.Boolean,System.Boolean,System.Boolean,Microsoft.WindowsAzure.Wapd.Acis.Contracts.IAcisServiceManagementExtension,Microsoft.WindowsAzure.Wapd.Acis.Contracts.IAcisSMEOperationProgressUpdater,Microsoft.WindowsAzure.Wapd.Acis.Contracts.IAcisSMEEndpoint)~Microsoft.WindowsAzure.Wapd.Acis.Contracts.IAcisSMEOperationResponse")]
[assembly: SuppressMessage("Reliability", "Liftr1004:Avoid calling System.Threading.Tasks.Task<TResult>.Result", Justification = "<Pending>", Scope = "member", Target = "~M:Microsoft.Liftr.ACIS.Logz.GetRPaaSObjectByMonitorOperation.GetRPaaSObjectByMonitor(System.String,Microsoft.WindowsAzure.Wapd.Acis.Contracts.IAcisServiceManagementExtension,Microsoft.WindowsAzure.Wapd.Acis.Contracts.IAcisSMEOperationProgressUpdater,Microsoft.WindowsAzure.Wapd.Acis.Contracts.IAcisSMEEndpoint)~Microsoft.WindowsAzure.Wapd.Acis.Contracts.IAcisSMEOperationResponse")]
[assembly: SuppressMessage("Reliability", "Liftr1004:Avoid calling System.Threading.Tasks.Task<TResult>.Result", Justification = "<Pending>", Scope = "member", Target = "~M:Microsoft.Liftr.ACIS.Logz.PatchRPaaSObjectByMonitorOperation.PatchRPaaSObjectByMonitor(System.String,System.String,Microsoft.WindowsAzure.Wapd.Acis.Contracts.IAcisServiceManagementExtension,Microsoft.WindowsAzure.Wapd.Acis.Contracts.IAcisSMEOperationProgressUpdater,Microsoft.WindowsAzure.Wapd.Acis.Contracts.IAcisSMEEndpoint)~Microsoft.WindowsAzure.Wapd.Acis.Contracts.IAcisSMEOperationResponse")]
[assembly: SuppressMessage("Reliability", "Liftr1004:Avoid calling System.Threading.Tasks.Task<TResult>.Result", Justification = "<Pending>", Scope = "member", Target = "~M:Microsoft.Liftr.ACIS.Logz.DeleteRPaaSObjectByMonitorOperation.DeleteRPaaSObjectByMonitor(System.String,Microsoft.WindowsAzure.Wapd.Acis.Contracts.IAcisServiceManagementExtension,Microsoft.WindowsAzure.Wapd.Acis.Contracts.IAcisSMEOperationProgressUpdater,Microsoft.WindowsAzure.Wapd.Acis.Contracts.IAcisSMEEndpoint)~Microsoft.WindowsAzure.Wapd.Acis.Contracts.IAcisSMEOperationResponse")]
[assembly: SuppressMessage("Reliability", "Liftr1004:Avoid calling System.Threading.Tasks.Task<TResult>.Result", Justification = "<Pending>", Scope = "member", Target = "~M:Microsoft.Liftr.ACIS.Logz.DeleteMonitorResourceByMonitorOperation.DeleteMonitorResourceByMonitor(System.String,System.String,System.Boolean,System.Boolean,System.Boolean,System.Boolean,System.Boolean,Microsoft.WindowsAzure.Wapd.Acis.Contracts.IAcisServiceManagementExtension,Microsoft.WindowsAzure.Wapd.Acis.Contracts.IAcisSMEOperationProgressUpdater,Microsoft.WindowsAzure.Wapd.Acis.Contracts.IAcisSMEEndpoint)~Microsoft.WindowsAzure.Wapd.Acis.Contracts.IAcisSMEOperationResponse")]
[assembly: SuppressMessage("Reliability", "Liftr1004:Avoid calling System.Threading.Tasks.Task<TResult>.Result", Justification = "<Pending>", Scope = "member", Target = "~M:Microsoft.Liftr.ACIS.Logz.UpdateMarketplaceEntitiesOperation.UpdateMarketplaceEntities(System.String,System.String,System.String,Microsoft.WindowsAzure.Wapd.Acis.Contracts.IAcisServiceManagementExtension,Microsoft.WindowsAzure.Wapd.Acis.Contracts.IAcisSMEOperationProgressUpdater,Microsoft.WindowsAzure.Wapd.Acis.Contracts.IAcisSMEEndpoint)~Microsoft.WindowsAzure.Wapd.Acis.Contracts.IAcisSMEOperationResponse")]
