//-----------------------------------------------------------------------------
// Copyright (c) Microsoft Corporation.  All rights reserved.
//-----------------------------------------------------------------------------
// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("StyleCop.CSharp.OrderingRules", "SA1201:Elements should appear in the correct order", Justification = "<Pending>", Scope = "member", Target = "~F:Microsoft.Liftr.ACIS.DatadogManagementExtension.s_redirectDllList")]
[assembly: SuppressMessage("Reliability", "Liftr1004:Avoid calling System.Threading.Tasks.Task<TResult>.Result", Justification = "<Pending>", Scope = "member", Target = "~M:Microsoft.Liftr.ACIS.GetDatadogMonitorOperation.GetDatadogMonitor(System.String,Microsoft.WindowsAzure.Wapd.Acis.Contracts.IAcisServiceManagementExtension,Microsoft.WindowsAzure.Wapd.Acis.Contracts.IAcisSMEOperationProgressUpdater,Microsoft.WindowsAzure.Wapd.Acis.Contracts.IAcisSMEEndpoint)~Microsoft.WindowsAzure.Wapd.Acis.Contracts.IAcisSMEOperationResponse")]
[assembly: SuppressMessage("Reliability", "Liftr1004:Avoid calling System.Threading.Tasks.Task<TResult>.Result", Justification = "<Pending>", Scope = "member", Target = "~M:Microsoft.Liftr.ACIS.Confluent.Configuration.FetchResourceInfoOperation.FetchInternalMetadata(System.String,Microsoft.WindowsAzure.Wapd.Acis.Contracts.IAcisServiceManagementExtension,Microsoft.WindowsAzure.Wapd.Acis.Contracts.IAcisSMEOperationProgressUpdater,Microsoft.WindowsAzure.Wapd.Acis.Contracts.IAcisSMEEndpoint)~Microsoft.WindowsAzure.Wapd.Acis.Contracts.IAcisSMEOperationResponse")]
[assembly: SuppressMessage("Performance", "CA1822:Mark members as static", Justification = "<Pending>", Scope = "member", Target = "~M:Microsoft.Liftr.ACIS.Confluent.Configuration.FetchResourceInfoOperation.FetchInternalMetadataAsync(System.String,Microsoft.WindowsAzure.Wapd.Acis.Contracts.IAcisServiceManagementExtension,Microsoft.WindowsAzure.Wapd.Acis.Contracts.IAcisSMEOperationProgressUpdater,Microsoft.WindowsAzure.Wapd.Acis.Contracts.IAcisSMEEndpoint)~System.Threading.Tasks.Task{Microsoft.WindowsAzure.Wapd.Acis.Contracts.IAcisSMEOperationResponse}")]
[assembly: SuppressMessage("Reliability", "Liftr1004:Avoid calling System.Threading.Tasks.Task<TResult>.Result", Justification = "<Pending>", Scope = "member", Target = "~M:Microsoft.Liftr.ACIS.Confluent.Configuration.FetchSaasResourceIdOperation.FetchSaasResourceId(System.String,Microsoft.WindowsAzure.Wapd.Acis.Contracts.IAcisServiceManagementExtension,Microsoft.WindowsAzure.Wapd.Acis.Contracts.IAcisSMEOperationProgressUpdater,Microsoft.WindowsAzure.Wapd.Acis.Contracts.IAcisSMEEndpoint)~Microsoft.WindowsAzure.Wapd.Acis.Contracts.IAcisSMEOperationResponse")]
[assembly: SuppressMessage("Performance", "CA1822:Mark members as static", Justification = "<Pending>", Scope = "member", Target = "~M:Microsoft.Liftr.ACIS.Confluent.Configuration.FetchSaasResourceIdOperation.FetchSaasResourceIdAsync(System.String,Microsoft.WindowsAzure.Wapd.Acis.Contracts.IAcisServiceManagementExtension,Microsoft.WindowsAzure.Wapd.Acis.Contracts.IAcisSMEOperationProgressUpdater,Microsoft.WindowsAzure.Wapd.Acis.Contracts.IAcisSMEEndpoint)~System.Threading.Tasks.Task{Microsoft.WindowsAzure.Wapd.Acis.Contracts.IAcisSMEOperationResponse}")]
[assembly: SuppressMessage("StyleCop.CSharp.OrderingRules", "SA1201:Elements should appear in the correct order", Justification = "<Pending>", Scope = "member", Target = "~F:Microsoft.Liftr.ACIS.Confluent.ConfluentExtension.s_redirectDllList")]
[assembly: SuppressMessage("Reliability", "Liftr1004:Avoid calling System.Threading.Tasks.Task<TResult>.Result", Justification = "<Pending>", Scope = "member", Target = "~M:Microsoft.Liftr.ACIS.Confluent.Configuration.FetchResourceInfoOperation.FetchInternalMetadata(System.String,System.String,Microsoft.WindowsAzure.Wapd.Acis.Contracts.IAcisServiceManagementExtension,Microsoft.WindowsAzure.Wapd.Acis.Contracts.IAcisSMEOperationProgressUpdater,Microsoft.WindowsAzure.Wapd.Acis.Contracts.IAcisSMEEndpoint)~Microsoft.WindowsAzure.Wapd.Acis.Contracts.IAcisSMEOperationResponse")]
[assembly: SuppressMessage("Performance", "CA1822:Mark members as static", Justification = "<Pending>", Scope = "member", Target = "~M:Microsoft.Liftr.ACIS.Confluent.Configuration.FetchResourceInfoOperation.FetchResourceInfoAsync(System.String,System.String,Microsoft.WindowsAzure.Wapd.Acis.Contracts.IAcisServiceManagementExtension,Microsoft.WindowsAzure.Wapd.Acis.Contracts.IAcisSMEOperationProgressUpdater,Microsoft.WindowsAzure.Wapd.Acis.Contracts.IAcisSMEEndpoint)~System.Threading.Tasks.Task{Microsoft.WindowsAzure.Wapd.Acis.Contracts.IAcisSMEOperationResponse}")]
[assembly: SuppressMessage("Reliability", "Liftr1004:Avoid calling System.Threading.Tasks.Task<TResult>.Result", Justification = "<Pending>", Scope = "member", Target = "~M:Microsoft.Liftr.ACIS.Confluent.Configuration.FetchSaasResourceIdOperation.FetchSaasResourceId(System.String,System.String,Microsoft.WindowsAzure.Wapd.Acis.Contracts.IAcisServiceManagementExtension,Microsoft.WindowsAzure.Wapd.Acis.Contracts.IAcisSMEOperationProgressUpdater,Microsoft.WindowsAzure.Wapd.Acis.Contracts.IAcisSMEEndpoint)~Microsoft.WindowsAzure.Wapd.Acis.Contracts.IAcisSMEOperationResponse")]
[assembly: SuppressMessage("Performance", "CA1822:Mark members as static", Justification = "<Pending>", Scope = "member", Target = "~M:Microsoft.Liftr.ACIS.Confluent.Configuration.FetchSaasResourceIdOperation.FetchSaasResourceIdAsync(System.String,System.String,Microsoft.WindowsAzure.Wapd.Acis.Contracts.IAcisServiceManagementExtension,Microsoft.WindowsAzure.Wapd.Acis.Contracts.IAcisSMEOperationProgressUpdater,Microsoft.WindowsAzure.Wapd.Acis.Contracts.IAcisSMEEndpoint)~System.Threading.Tasks.Task{Microsoft.WindowsAzure.Wapd.Acis.Contracts.IAcisSMEOperationResponse}")]
[assembly: SuppressMessage("Reliability", "Liftr1004:Avoid calling System.Threading.Tasks.Task<TResult>.Result", Justification = "<Pending>", Scope = "member", Target = "~M:Microsoft.Liftr.ACIS.Confluent.Configuration.FetchResourceInfoOperation.FetchResourceInfo(System.String,System.String,Microsoft.WindowsAzure.Wapd.Acis.Contracts.IAcisServiceManagementExtension,Microsoft.WindowsAzure.Wapd.Acis.Contracts.IAcisSMEOperationProgressUpdater,Microsoft.WindowsAzure.Wapd.Acis.Contracts.IAcisSMEEndpoint)~Microsoft.WindowsAzure.Wapd.Acis.Contracts.IAcisSMEOperationResponse")]
[assembly: SuppressMessage("Performance", "CA1822:Mark members as static", Justification = "<Pending>", Scope = "member", Target = "~M:Microsoft.Liftr.ACIS.Confluent.Configuration.FetchResourceInfoOperation.FetchResourceInfo(System.String,System.String,Microsoft.WindowsAzure.Wapd.Acis.Contracts.IAcisServiceManagementExtension,Microsoft.WindowsAzure.Wapd.Acis.Contracts.IAcisSMEOperationProgressUpdater,Microsoft.WindowsAzure.Wapd.Acis.Contracts.IAcisSMEEndpoint)~Microsoft.WindowsAzure.Wapd.Acis.Contracts.IAcisSMEOperationResponse")]
[assembly: SuppressMessage("Performance", "CA1822:Mark members as static", Justification = "<Pending>", Scope = "member", Target = "~M:Microsoft.Liftr.ACIS.Confluent.Configuration.FetchSaasResourceIdOperation.FetchSaasResourceId(System.String,System.String,Microsoft.WindowsAzure.Wapd.Acis.Contracts.IAcisServiceManagementExtension,Microsoft.WindowsAzure.Wapd.Acis.Contracts.IAcisSMEOperationProgressUpdater,Microsoft.WindowsAzure.Wapd.Acis.Contracts.IAcisSMEEndpoint)~Microsoft.WindowsAzure.Wapd.Acis.Contracts.IAcisSMEOperationResponse")]
[assembly: SuppressMessage("Reliability", "Liftr1004:Avoid calling System.Threading.Tasks.Task<TResult>.Result", Justification = "<Pending>", Scope = "member", Target = "~M:Microsoft.Liftr.ACIS.Confluent.Partner.CreateResourceFailedWebhookOperation.CreateResourceFailedWebhook(Microsoft.WindowsAzure.Wapd.Acis.Contracts.IAcisServiceManagementExtension,Microsoft.WindowsAzure.Wapd.Acis.Contracts.IAcisSMEOperationProgressUpdater,Microsoft.WindowsAzure.Wapd.Acis.Contracts.IAcisSMEEndpoint)~Microsoft.WindowsAzure.Wapd.Acis.Contracts.IAcisSMEOperationResponse")]
[assembly: SuppressMessage("Performance", "CA1822:Mark members as static", Justification = "<Pending>", Scope = "member", Target = "~M:Microsoft.Liftr.ACIS.Confluent.Partner.CreateResourceFailedWebhookOperation.CreateResourceFailedWebhook(Microsoft.WindowsAzure.Wapd.Acis.Contracts.IAcisServiceManagementExtension,Microsoft.WindowsAzure.Wapd.Acis.Contracts.IAcisSMEOperationProgressUpdater,Microsoft.WindowsAzure.Wapd.Acis.Contracts.IAcisSMEEndpoint)~Microsoft.WindowsAzure.Wapd.Acis.Contracts.IAcisSMEOperationResponse")]
[assembly: SuppressMessage("Reliability", "Liftr1004:Avoid calling System.Threading.Tasks.Task<TResult>.Result", Justification = "<Pending>", Scope = "member", Target = "~M:Microsoft.Liftr.ACIS.Confluent.Partner.ActivationFailedWebhookOperation.ActivationFailedWebhook(Microsoft.WindowsAzure.Wapd.Acis.Contracts.IAcisServiceManagementExtension,Microsoft.WindowsAzure.Wapd.Acis.Contracts.IAcisSMEOperationProgressUpdater,Microsoft.WindowsAzure.Wapd.Acis.Contracts.IAcisSMEEndpoint)~Microsoft.WindowsAzure.Wapd.Acis.Contracts.IAcisSMEOperationResponse")]
[assembly: SuppressMessage("Performance", "CA1822:Mark members as static", Justification = "<Pending>", Scope = "member", Target = "~M:Microsoft.Liftr.ACIS.Confluent.Partner.ActivationFailedWebhookOperation.ActivationFailedWebhook(Microsoft.WindowsAzure.Wapd.Acis.Contracts.IAcisServiceManagementExtension,Microsoft.WindowsAzure.Wapd.Acis.Contracts.IAcisSMEOperationProgressUpdater,Microsoft.WindowsAzure.Wapd.Acis.Contracts.IAcisSMEEndpoint)~Microsoft.WindowsAzure.Wapd.Acis.Contracts.IAcisSMEOperationResponse")]
[assembly: SuppressMessage("Reliability", "Liftr1004:Avoid calling System.Threading.Tasks.Task<TResult>.Result", Justification = "<Pending>", Scope = "member", Target = "~M:Microsoft.Liftr.ACIS.Confluent.Partner.DeleteResourceFailedWebhookOperation.DeleteResourceFailedWebhook(Microsoft.WindowsAzure.Wapd.Acis.Contracts.IAcisServiceManagementExtension,Microsoft.WindowsAzure.Wapd.Acis.Contracts.IAcisSMEOperationProgressUpdater,Microsoft.WindowsAzure.Wapd.Acis.Contracts.IAcisSMEEndpoint)~Microsoft.WindowsAzure.Wapd.Acis.Contracts.IAcisSMEOperationResponse")]
[assembly: SuppressMessage("Performance", "CA1822:Mark members as static", Justification = "<Pending>", Scope = "member", Target = "~M:Microsoft.Liftr.ACIS.Confluent.Partner.DeleteResourceFailedWebhookOperation.DeleteResourceFailedWebhook(Microsoft.WindowsAzure.Wapd.Acis.Contracts.IAcisServiceManagementExtension,Microsoft.WindowsAzure.Wapd.Acis.Contracts.IAcisSMEOperationProgressUpdater,Microsoft.WindowsAzure.Wapd.Acis.Contracts.IAcisSMEEndpoint)~Microsoft.WindowsAzure.Wapd.Acis.Contracts.IAcisSMEOperationResponse")]
[assembly: SuppressMessage("Performance", "CA1822:Mark members as static", Justification = "<Pending>", Scope = "member", Target = "~M:Microsoft.Liftr.ACIS.Confluent.Partner.ActivationFailedWebhookOperation.ActivationFailedWebhook(System.String,System.String,Microsoft.WindowsAzure.Wapd.Acis.Contracts.IAcisServiceManagementExtension,Microsoft.WindowsAzure.Wapd.Acis.Contracts.IAcisSMEOperationProgressUpdater,Microsoft.WindowsAzure.Wapd.Acis.Contracts.IAcisSMEEndpoint)~Microsoft.WindowsAzure.Wapd.Acis.Contracts.IAcisSMEOperationResponse")]
[assembly: SuppressMessage("Reliability", "Liftr1004:Avoid calling System.Threading.Tasks.Task<TResult>.Result", Justification = "<Pending>", Scope = "member", Target = "~M:Microsoft.Liftr.ACIS.Confluent.Partner.ActivationFailedWebhookOperation.ActivationFailedWebhook(System.String,System.String,Microsoft.WindowsAzure.Wapd.Acis.Contracts.IAcisServiceManagementExtension,Microsoft.WindowsAzure.Wapd.Acis.Contracts.IAcisSMEOperationProgressUpdater,Microsoft.WindowsAzure.Wapd.Acis.Contracts.IAcisSMEEndpoint)~Microsoft.WindowsAzure.Wapd.Acis.Contracts.IAcisSMEOperationResponse")]
[assembly: SuppressMessage("Performance", "CA1822:Mark members as static", Justification = "<Pending>", Scope = "member", Target = "~M:Microsoft.Liftr.ACIS.Confluent.Partner.DeleteResourceFailedWebhookOperation.DeleteResourceFailedWebhook(System.String,System.String,Microsoft.WindowsAzure.Wapd.Acis.Contracts.IAcisServiceManagementExtension,Microsoft.WindowsAzure.Wapd.Acis.Contracts.IAcisSMEOperationProgressUpdater,Microsoft.WindowsAzure.Wapd.Acis.Contracts.IAcisSMEEndpoint)~Microsoft.WindowsAzure.Wapd.Acis.Contracts.IAcisSMEOperationResponse")]
[assembly: SuppressMessage("Reliability", "Liftr1004:Avoid calling System.Threading.Tasks.Task<TResult>.Result", Justification = "<Pending>", Scope = "member", Target = "~M:Microsoft.Liftr.ACIS.Confluent.Partner.DeleteResourceFailedWebhookOperation.DeleteResourceFailedWebhook(System.String,System.String,Microsoft.WindowsAzure.Wapd.Acis.Contracts.IAcisServiceManagementExtension,Microsoft.WindowsAzure.Wapd.Acis.Contracts.IAcisSMEOperationProgressUpdater,Microsoft.WindowsAzure.Wapd.Acis.Contracts.IAcisSMEEndpoint)~Microsoft.WindowsAzure.Wapd.Acis.Contracts.IAcisSMEOperationResponse")]
