//-----------------------------------------------------------------------------
// Copyright (c) Microsoft Corporation.  All rights reserved.
//-----------------------------------------------------------------------------
// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("StyleCop.CSharp.OrderingRules", "SA1201:Elements should appear in the correct order", Justification = "<Pending>", Scope = "member", Target = "~F:Microsoft.Liftr.ACIS.NginxManagementExtension.s_redirectDllList")]
[assembly: SuppressMessage("Design", "CA1062:Validate arguments of public methods", Justification = "<Pending>", Scope = "member", Target = "~M:Microsoft.Liftr.ACIS.Nginx.Common.Utilities.CallOperationAsync(System.String,Microsoft.WindowsAzure.Wapd.Acis.Contracts.IAcisServiceManagementExtension,Microsoft.WindowsAzure.Wapd.Acis.Contracts.IAcisSMEOperationProgressUpdater,Microsoft.WindowsAzure.Wapd.Acis.Contracts.IAcisSMEEndpoint,System.String,System.String)~System.Threading.Tasks.Task{Microsoft.WindowsAzure.Wapd.Acis.Contracts.IAcisSMEOperationResponse}")]
[assembly: SuppressMessage("Design", "Liftr1201:License header is missing or inconsistent", Justification = "<Pending>", Scope = "namespace", Target = "~N:Microsoft.Liftr.ACIS.Nginx.Common")]
[assembly: SuppressMessage("Performance", "CA1822:Mark members as static", Justification = "<Pending>", Scope = "member", Target = "~M:Microsoft.Liftr.ACIS.Nginx.Marketplace.GetMarketplaceResourceByDeploymentOperation.GetMarketplaceResourceByDeployment(System.String,Microsoft.WindowsAzure.Wapd.Acis.Contracts.IAcisServiceManagementExtension,Microsoft.WindowsAzure.Wapd.Acis.Contracts.IAcisSMEOperationProgressUpdater,Microsoft.WindowsAzure.Wapd.Acis.Contracts.IAcisSMEEndpoint)~Microsoft.WindowsAzure.Wapd.Acis.Contracts.IAcisSMEOperationResponse")]
[assembly: SuppressMessage("Reliability", "Liftr1004:Avoid calling System.Threading.Tasks.Task<TResult>.Result", Justification = "<Pending>", Scope = "member", Target = "~M:Microsoft.Liftr.ACIS.Nginx.Marketplace.GetMarketplaceResourceByDeploymentOperation.GetMarketplaceResourceByDeployment(System.String,Microsoft.WindowsAzure.Wapd.Acis.Contracts.IAcisServiceManagementExtension,Microsoft.WindowsAzure.Wapd.Acis.Contracts.IAcisSMEOperationProgressUpdater,Microsoft.WindowsAzure.Wapd.Acis.Contracts.IAcisSMEEndpoint)~Microsoft.WindowsAzure.Wapd.Acis.Contracts.IAcisSMEOperationResponse")]
[assembly: SuppressMessage("Performance", "CA1822:Mark members as static", Justification = "<Pending>", Scope = "member", Target = "~M:Microsoft.Liftr.ACIS.Nginx.RPaaS.GetNginxDeploymentOperation.GetNginxDeployment(System.String,Microsoft.WindowsAzure.Wapd.Acis.Contracts.IAcisServiceManagementExtension,Microsoft.WindowsAzure.Wapd.Acis.Contracts.IAcisSMEOperationProgressUpdater,Microsoft.WindowsAzure.Wapd.Acis.Contracts.IAcisSMEEndpoint)~Microsoft.WindowsAzure.Wapd.Acis.Contracts.IAcisSMEOperationResponse")]
[assembly: SuppressMessage("Reliability", "Liftr1004:Avoid calling System.Threading.Tasks.Task<TResult>.Result", Justification = "<Pending>", Scope = "member", Target = "~M:Microsoft.Liftr.ACIS.Nginx.RPaaS.GetNginxDeploymentOperation.GetNginxDeployment(System.String,Microsoft.WindowsAzure.Wapd.Acis.Contracts.IAcisServiceManagementExtension,Microsoft.WindowsAzure.Wapd.Acis.Contracts.IAcisSMEOperationProgressUpdater,Microsoft.WindowsAzure.Wapd.Acis.Contracts.IAcisSMEEndpoint)~Microsoft.WindowsAzure.Wapd.Acis.Contracts.IAcisSMEOperationResponse")]
[assembly: SuppressMessage("Performance", "CA1822:Mark members as static", Justification = "<Pending>", Scope = "member", Target = "~M:Microsoft.Liftr.ACIS.Nginx.RPaaS.ListAllDeploymentsBySubIdOperation.ListAllDeploymentsBySubId(System.String,Microsoft.WindowsAzure.Wapd.Acis.Contracts.IAcisServiceManagementExtension,Microsoft.WindowsAzure.Wapd.Acis.Contracts.IAcisSMEOperationProgressUpdater,Microsoft.WindowsAzure.Wapd.Acis.Contracts.IAcisSMEEndpoint)~Microsoft.WindowsAzure.Wapd.Acis.Contracts.IAcisSMEOperationResponse")]
[assembly: SuppressMessage("Reliability", "Liftr1004:Avoid calling System.Threading.Tasks.Task<TResult>.Result", Justification = "<Pending>", Scope = "member", Target = "~M:Microsoft.Liftr.ACIS.Nginx.RPaaS.ListAllDeploymentsBySubIdOperation.ListAllDeploymentsBySubId(System.String,Microsoft.WindowsAzure.Wapd.Acis.Contracts.IAcisServiceManagementExtension,Microsoft.WindowsAzure.Wapd.Acis.Contracts.IAcisSMEOperationProgressUpdater,Microsoft.WindowsAzure.Wapd.Acis.Contracts.IAcisSMEEndpoint)~Microsoft.WindowsAzure.Wapd.Acis.Contracts.IAcisSMEOperationResponse")]
[assembly: SuppressMessage("Performance", "CA1822:Mark members as static", Justification = "<Pending>", Scope = "member", Target = "~M:Microsoft.Liftr.ACIS.Nginx.Partner.GetOrgForSubIdOperation.GetOrgForSubId(System.String,Microsoft.WindowsAzure.Wapd.Acis.Contracts.IAcisServiceManagementExtension,Microsoft.WindowsAzure.Wapd.Acis.Contracts.IAcisSMEOperationProgressUpdater,Microsoft.WindowsAzure.Wapd.Acis.Contracts.IAcisSMEEndpoint)~Microsoft.WindowsAzure.Wapd.Acis.Contracts.IAcisSMEOperationResponse")]
[assembly: SuppressMessage("Reliability", "Liftr1004:Avoid calling System.Threading.Tasks.Task<TResult>.Result", Justification = "<Pending>", Scope = "member", Target = "~M:Microsoft.Liftr.ACIS.Nginx.Partner.GetOrgForSubIdOperation.GetOrgForSubId(System.String,Microsoft.WindowsAzure.Wapd.Acis.Contracts.IAcisServiceManagementExtension,Microsoft.WindowsAzure.Wapd.Acis.Contracts.IAcisSMEOperationProgressUpdater,Microsoft.WindowsAzure.Wapd.Acis.Contracts.IAcisSMEEndpoint)~Microsoft.WindowsAzure.Wapd.Acis.Contracts.IAcisSMEOperationResponse")]
[assembly: SuppressMessage("Performance", "CA1822:Mark members as static", Justification = "<Pending>", Scope = "member", Target = "~M:Microsoft.Liftr.ACIS.Nginx.Partner.FetchListOfDeploymentsForSubIdOperation.FetchListOfDeploymentsForSubId(System.String,System.String,Microsoft.WindowsAzure.Wapd.Acis.Contracts.IAcisServiceManagementExtension,Microsoft.WindowsAzure.Wapd.Acis.Contracts.IAcisSMEOperationProgressUpdater,Microsoft.WindowsAzure.Wapd.Acis.Contracts.IAcisSMEEndpoint)~Microsoft.WindowsAzure.Wapd.Acis.Contracts.IAcisSMEOperationResponse")]
[assembly: SuppressMessage("Reliability", "Liftr1004:Avoid calling System.Threading.Tasks.Task<TResult>.Result", Justification = "<Pending>", Scope = "member", Target = "~M:Microsoft.Liftr.ACIS.Nginx.Partner.FetchListOfDeploymentsForSubIdOperation.FetchListOfDeploymentsForSubId(System.String,System.String,Microsoft.WindowsAzure.Wapd.Acis.Contracts.IAcisServiceManagementExtension,Microsoft.WindowsAzure.Wapd.Acis.Contracts.IAcisSMEOperationProgressUpdater,Microsoft.WindowsAzure.Wapd.Acis.Contracts.IAcisSMEEndpoint)~Microsoft.WindowsAzure.Wapd.Acis.Contracts.IAcisSMEOperationResponse")]
